package cn.guba.igu8.db.mysqlModel.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public M setPasswd(java.lang.String passwd) {
		set("passwd", passwd);
		return (M)this;
	}

	public java.lang.String getPasswd() {
		return get("passwd");
	}

	public M setCreatTime(java.lang.Long creatTime) {
		set("creatTime", creatTime);
		return (M)this;
	}

	public java.lang.Long getCreatTime() {
		return get("creatTime");
	}

	public M setPhoneNumber(java.lang.Long phoneNumber) {
		set("phoneNumber", phoneNumber);
		return (M)this;
	}

	public java.lang.Long getPhoneNumber() {
		return get("phoneNumber");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setInviterUid(java.lang.Long inviterUid) {
		set("inviterUid", inviterUid);
		return (M)this;
	}

	public java.lang.Long getInviterUid() {
		return get("inviterUid");
	}

}
