package cn.guba.igu8.db.mysqlModel.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUservipinfo<M extends BaseUservipinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUid(java.lang.Long uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.Long getUid() {
		return getLong("uid");
	}

	public M setVipTypeId(java.lang.Integer vipTypeId) {
		set("vipTypeId", vipTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getVipTypeId() {
		return getInt("vipTypeId");
	}

	public M setVipEndTime(java.lang.Long vipEndTime) {
		set("vipEndTime", vipEndTime);
		return (M)this;
	}
	
	public java.lang.Long getVipEndTime() {
		return getLong("vipEndTime");
	}

	public M setConcernedTeacherId(java.lang.Long concernedTeacherId) {
		set("concernedTeacherId", concernedTeacherId);
		return (M)this;
	}
	
	public java.lang.Long getConcernedTeacherId() {
		return getLong("concernedTeacherId");
	}

	public M setSendEmail(java.lang.String sendEmail) {
		set("sendEmail", sendEmail);
		return (M)this;
	}
	
	public java.lang.String getSendEmail() {
		return getStr("sendEmail");
	}

	public M setSendSms(java.lang.Boolean sendSms) {
		set("sendSms", sendSms);
		return (M)this;
	}
	
	public java.lang.Boolean getSendSms() {
		return get("sendSms");
	}

	public M setShowUrl(java.lang.Boolean showUrl) {
		set("showUrl", showUrl);
		return (M)this;
	}
	
	public java.lang.Boolean getShowUrl() {
		return get("showUrl");
	}

	public M setVipGroup(java.lang.String vipGroup) {
		set("vipGroup", vipGroup);
		return (M)this;
	}
	
	public java.lang.String getVipGroup() {
		return getStr("vipGroup");
	}

}
