package cn.guba.igu8.db.mysqlModel.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserdiscountinfo<M extends BaseUserdiscountinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setUid(java.lang.Long uid) {
		set("uid", uid);
		return (M)this;
	}

	public java.lang.Long getUid() {
		return get("uid");
	}

	public M setDiscountMoney(java.lang.Integer discountMoney) {
		set("discountMoney", discountMoney);
		return (M)this;
	}

	public java.lang.Integer getDiscountMoney() {
		return get("discountMoney");
	}

	public M setDiscountEndTime(java.lang.Long discountEndTime) {
		set("discountEndTime", discountEndTime);
		return (M)this;
	}

	public java.lang.Long getDiscountEndTime() {
		return get("discountEndTime");
	}

	public M setDiscountFromUid(java.lang.Long discountFromUid) {
		set("discountFromUid", discountFromUid);
		return (M)this;
	}

	public java.lang.Long getDiscountFromUid() {
		return get("discountFromUid");
	}

	public M setCurTime(java.lang.Long curTime) {
		set("curTime", curTime);
		return (M)this;
	}

	public java.lang.Long getCurTime() {
		return get("curTime");
	}

}
