package cn.guba.igu8.db.mysqlModel.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setPfId(java.lang.Integer pfId) {
		set("pfId", pfId);
		return (M)this;
	}

	public java.lang.Integer getPfId() {
		return get("pfId");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setBuyEndTime(java.lang.Long buyEndTime) {
		set("buyEndTime", buyEndTime);
		return (M)this;
	}

	public java.lang.Long getBuyEndTime() {
		return get("buyEndTime");
	}

	public M setPfVipUid(java.lang.Integer pfVipUid) {
		set("pfVipUid", pfVipUid);
		return (M)this;
	}

	public java.lang.Integer getPfVipUid() {
		return get("pfVipUid");
	}

	public M setVipTypeId(java.lang.Integer vipTypeId) {
		set("vipTypeId", vipTypeId);
		return (M)this;
	}

	public java.lang.Integer getVipTypeId() {
		return get("vipTypeId");
	}

}
