package cn.guba.igu8.db.mysqlModel;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("eova_menu", "id", EovaMenu.class);
		arp.addMapping("igpcontent", "lid", Igpcontent.class);
		arp.addMapping("rechargelog", "id", Rechargelog.class);
		arp.addMapping("teacher", "id", Teacher.class);
		arp.addMapping("tj_deal_info", "id", TjDealInfo.class);
		arp.addMapping("tj_unit_info", "id", TjUnitInfo.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("userdiscountinfo", "id", Userdiscountinfo.class);
		arp.addMapping("uservipinfo", "id", Uservipinfo.class);
		arp.addMapping("viptype", "id", Viptype.class);
	}
}

