package cn.guba.igu8.db.mysqlModel;

import cn.guba.igu8.db.mysqlModel.base.BaseEovaMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EovaMenu extends BaseEovaMenu<EovaMenu> {
	public static final EovaMenu dao = new EovaMenu().dao();
}
