package cn.guba.igu8.db.mysqlModel;

import cn.guba.igu8.db.mysqlModel.base.BaseIgpcontent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Igpcontent extends BaseIgpcontent<Igpcontent> {
	public static final Igpcontent dao = new Igpcontent().dao();
}
