package cn.guba.igu8.db.mysqlModel;

import cn.guba.igu8.db.mysqlModel.base.BaseRechargelog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rechargelog extends BaseRechargelog<Rechargelog> {
	public static final Rechargelog dao = new Rechargelog().dao();
}
