package cn.guba.igu8.db.mysqlModel;

import cn.guba.igu8.db.mysqlModel.base.BaseTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher().dao();
}
