package cn.guba.igu8.db.mysqlModel;

import cn.guba.igu8.db.mysqlModel.base.BaseUserdiscountinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userdiscountinfo extends BaseUserdiscountinfo<Userdiscountinfo> {
	public static final Userdiscountinfo dao = new Userdiscountinfo().dao();
}
