package cn.guba.igu8.db.mysqlModel;

import cn.guba.igu8.db.mysqlModel.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
}
