package cn.guba.igu8.db.mysqlModel;

import cn.guba.igu8.db.mysqlModel.base.BaseUservipinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Uservipinfo extends BaseUservipinfo<Uservipinfo> {
	public static final Uservipinfo dao = new Uservipinfo().dao();
}
