package cn.guba.igu8.db.mysqlModel;

import cn.guba.igu8.db.mysqlModel.base.BaseViptype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Viptype extends BaseViptype<Viptype> {
	public static final Viptype dao = new Viptype().dao();
}
